name: JoinActionbar
version: '${project.version}'
main: me.malajis.joinactionbar.Main
api-version: '1.13'
author: Malajis
commands:
  jareload:
    description: "JoinActionbar重载命令"
    permission: joinactionbar.jareload
permissions:
  joinactionbar.jareload:
    default: op
    description: "重载JoinActionbar配置"
  joinactionbar.op:
    default: false
    description: "OP管理员进服/退服提示 (可在config.yml中自定义权限组)"
  joinactionbar.vip:
    default: false
    description: "VIP进服/退服提示 (可在config.yml中自定义权限组)"
