#当一个玩家进入服务器后所有玩家收到的消息-actionbar
JoinMessage: "&b欢迎玩家 &e%player% &b加入测试子服"
JoinMessageOP: "&6欢迎管理员 &c%player% &6加入测试子服"
JoinMessageVIP: "&d欢迎VIP &e%player% &d加入测试子服"
#当一个玩家退出服务器后所有玩家收到的消息-actionbar
QuitMessage: "&c玩家 &e%player% &c离开了测试子服"
QuitMessageOP: "&c管理员 &e%player% &c离开了测试子服"
QuitMessageVIP: "&cVIP &e%player% &c离开了测试子服"
#重载返回
Message:
  reload: "&aBetterAccess 重载完成"